apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ngoldz7ho-python
  janus-idp.io/tekton: ngoldz7ho-python
  backstage.io/kubernetes-id: ngoldz7ho-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ngoldz7ho-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
